#Faça um programa que leia um número inteiro qualquer e mostre sua tabuada.
from time import sleep
print('TABUADA')
sleep(0.5)
num = int(input('Insira um número para mostrar sua tabuada: '))
print('Calculando...')
sleep(1.5)
print(f'{num} x {1}  = {num*1}')
print(f'{num} x {2}  = {num*2}')
print(f'{num} x {3}  = {num*3}')
print(f'{num} x {4}  = {num*4}')
print(f'{num} x {5}  = {num*5}')
print(f'{num} x {6}  = {num*6}')
print(f'{num} x {7}  = {num*7}')
print(f'{num} x {8}  = {num*8}')
print(f'{num} x {9}  = {num*9}')
print(f'{num} x {10} = {num*10}\n')
