#Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas informações possíveis sobre ele
a = input('Digite algo: ')
print(f'O tipo primitivo do valor digitado é {type(a)}')
print(f'É apenas maiúscula? {a.isupper()}')
print(f'É apenas minúsculo? {a.islower()}')
print(f'Primeira letra é maiúscula (capitalizada)? {a.istitle()}')
print(f'É apenas espaço? {a.isspace()}')
print(f'É numérico? {a.isnumeric()}')
print(f'É alfabético? {a.isalpha()}')
print(f'É alfanumérico? {a.isalnum()}')
